namespace AiKnowledgeTransfer.Application.Diagnostics;

public sealed record OperationalHealthOptions(
    string AppDataPath,
    string UploadStoragePath,
    string ProjectStorePath,
    string AuditLogPath,
    string PersistenceProvider,
    string? DatabaseProvider,
    string? DatabaseConnectionString,
    string DatabaseSchemaMode,
    string AiProvider,
    string AiModel,
    string AiBaseUrl,
    bool AiApiKeyConfigured,
    int MaxAnalysisChunksPerDocument,
    int MaxAnalysisExtractedCharacters,
    int MaxExtractionChunks,
    int MaxExtractionChunkCharacters,
    string AuthMode,
    string? AuthAuthority,
    string? AuthClientId,
    string AuthRoleClaimType,
    string TenancyMode,
    string TenantClaimType,
    string DefaultTenantId,
    string TenantBoundaryMode = "Unspecified",
    string? TenantBoundaryOwner = null,
    string SecretStoreMode = "Environment",
    string? SecretStoreProvider = null,
    string? SecretRotationOwner = null,
    string DeploymentStrategy = "SingleSlot",
    string? DeploymentApprovalOwner = null);
